"use client";

import { useEffect } from "react";

type Lang = "ro" | "en" | "ru" | "ua";

const labels: Record<Lang, {
  title: string;
  desc: string;
  btn: string;
  clinic: string;
  generated: string;
}> = {
  ro: {
    title: "Salvează articolul",
    desc: "Descarcă articolul ca document Word pentru citire offline.",
    btn: "Descarcă DOC",
    clinic: "Centrul Medical Revimed PLUS+",
    generated: "Document generat de Revimed PLUS+"
  },
  en: {
    title: "Save article",
    desc: "Download this article as a Word document for offline reading.",
    btn: "Download DOC",
    clinic: "Revimed PLUS+ Medical Center",
    generated: "Document generated by Revimed PLUS+"
  },
  ru: {
    title: "Сохранить статью",
    desc: "Скачайте статью как Word-документ для чтения офлайн.",
    btn: "Скачать DOC",
    clinic: "Медицинский центр Revimed PLUS+",
    generated: "Документ создан Revimed PLUS+"
  },
  ua: {
    title: "Зберегти статтю",
    desc: "Завантажте статтю як Word-документ для читання офлайн.",
    btn: "Завантажити DOC",
    clinic: "Медичний центр Revimed PLUS+",
    generated: "Документ створено Revimed PLUS+"
  }
};

function getLang(): Lang {
  const first = window.location.pathname.split("/").filter(Boolean)[0];
  if (first === "en" || first === "ru" || first === "ua") return first;
  return "ro";
}

function isBlogPostPage() {
  const parts = window.location.pathname.split("/").filter(Boolean);
  const blogIndex = parts.indexOf("blog");
  return blogIndex >= 0 && parts.length > blogIndex + 1;
}

function safeFileName(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9а-яёіїєґ\u0400-\u04ff]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "revimed-articol";
}

function buildDocHtml(title: string, articleHtml: string, lang: Lang) {
  const t = labels[lang];
  const logoUrl = `${window.location.origin}/images/logo.png`;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>
    @page { margin: 2cm; }
    body {
      font-family: Arial, Helvetica, sans-serif;
      color: #10233f;
      line-height: 1.55;
      font-size: 14px;
    }
    .top-logo {
      text-align: right;
      margin-bottom: 22px;
    }
    .top-logo img,
    .bottom-logo img {
      width: 150px;
      height: auto;
    }
    h1 {
      font-size: 28px;
      line-height: 1.15;
      color: #08234a;
      margin: 0 0 18px;
    }
    h2, h3 {
      color: #08234a;
      margin-top: 22px;
      margin-bottom: 10px;
    }
    p {
      margin: 0 0 12px;
    }
    .box, .blogContentHeading, .blogAutoHeading {
      background: #eef8ff;
      border-left: 4px solid #0b8fd8;
      padding: 10px 12px;
      border-radius: 8px;
      font-weight: bold;
      color: #08234a;
    }
    .footer-note {
      margin-top: 32px;
      padding-top: 12px;
      border-top: 1px solid #dcecf8;
      color: #64748b;
      font-size: 12px;
    }
    .bottom-logo {
      text-align: right;
      margin-top: 18px;
    }
  </style>
</head>
<body>
  <div class="top-logo">
    <img src="${logoUrl}" alt="Revimed PLUS+" />
  </div>

  <h1>${title}</h1>

  <main>
    ${articleHtml}
  </main>

  <div class="footer-note">
    ${t.generated}<br />
    ${t.clinic}<br />
    022 60 50 60 · +373 79 422 908
  </div>

  <div class="bottom-logo">
    <img src="${logoUrl}" alt="Revimed PLUS+" />
  </div>
</body>
</html>`;
}

function downloadDoc() {
  const lang = getLang();
  const title =
    document.querySelector("section.blogPostHero h1")?.textContent?.trim() ||
    document.querySelector("h1")?.textContent?.trim() ||
    "Revimed PLUS+";

  const content =
    document.querySelector(".blogReadableContent") ||
    document.querySelector(".blogPostArticle") ||
    document.querySelector("article");

  if (!content) return;

  const clone = content.cloneNode(true) as HTMLElement;

  clone.querySelectorAll(
    ".blogExportBox, .blogExportBtn, button, script, style"
  ).forEach((el) => el.remove());

  clone.querySelectorAll<HTMLElement>("[style]").forEach((el) => {
    el.removeAttribute("style");
  });

  const html = buildDocHtml(title, clone.innerHTML, lang);
  const blob = new Blob(["\ufeff", html], {
    type: "application/msword;charset=utf-8"
  });

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safeFileName(title)}-revimed.doc`;
  document.body.appendChild(a);
  a.click();
  a.remove();

  window.setTimeout(() => URL.revokeObjectURL(url), 500);
}

function addButton() {
  if (!isBlogPostPage()) return;

  const article =
    document.querySelector(".blogPostArticle") ||
    document.querySelector(".blogArticleCard") ||
    document.querySelector("article");

  if (!article) return;
  if (article.querySelector(".blogExportBox")) return;

  const lang = getLang();
  const t = labels[lang];

  const box = document.createElement("div");
  box.className = "blogExportBox";
  box.innerHTML = `
    <div class="blogExportText">
      <strong>${t.title}</strong>
      <span>${t.desc}</span>
    </div>
    <button type="button" class="blogExportBtn">${t.btn}</button>
  `;

  const btn = box.querySelector<HTMLButtonElement>(".blogExportBtn");
  btn?.addEventListener("click", downloadDoc);

  article.appendChild(box);
}

export default function BlogDocumentDownload() {
  useEffect(() => {
    addButton();

    const observer = new MutationObserver(() => addButton());
    observer.observe(document.body, { childList: true, subtree: true });

    return () => observer.disconnect();
  }, []);

  return null;
}
