"use client";

import { useEffect } from "react";

type Lang = "ro" | "en" | "ru" | "ua";

const labels: Record<Lang, {
  saveTitle: string;
  saveDesc: string;
  saveBtn: string;
  generated: string;
  clinic: string;
}> = {
  ro: {
    saveTitle: "Salvează articolul",
    saveDesc: "Descarcă articolul ca document pentru citire offline.",
    saveBtn: "Descarcă document",
    generated: "Document generat de Revimed PLUS+",
    clinic: "Centrul Medical Revimed PLUS+"
  },
  en: {
    saveTitle: "Save article",
    saveDesc: "Download this article as a document for offline reading.",
    saveBtn: "Download document",
    generated: "Document generated by Revimed PLUS+",
    clinic: "Revimed PLUS+ Medical Center"
  },
  ru: {
    saveTitle: "Сохранить статью",
    saveDesc: "Скачайте статью как документ для чтения офлайн.",
    saveBtn: "Скачать документ",
    generated: "Документ создан Revimed PLUS+",
    clinic: "Медицинский центр Revimed PLUS+"
  },
  ua: {
    saveTitle: "Зберегти статтю",
    saveDesc: "Завантажте статтю як документ для читання офлайн.",
    saveBtn: "Завантажити документ",
    generated: "Документ створено Revimed PLUS+",
    clinic: "Медичний центр Revimed PLUS+"
  }
};

function getLang(): Lang {
  const first = window.location.pathname.split("/").filter(Boolean)[0];
  if (first === "en" || first === "ru" || first === "ua") return first;
  return "ro";
}

function isBlogPostPage() {
  const parts = window.location.pathname.split("/").filter(Boolean);
  const blogIndex = parts.indexOf("blog");
  return blogIndex >= 0 && parts.length > blogIndex + 1;
}

function normalize(value: string) {
  return value.replace(/\s+/g, " ").trim();
}

function safeFileName(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9а-яёіїєґ\u0400-\u04ff]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 90) || "revimed-articol";
}

function looksLikeHeading(text: string) {
  const t = normalize(text);

  if (t.length < 8 || t.length > 140) return false;

  return (
    /^\d+[\.\)]\s+/.test(t) ||
    /^✓\s*\d+[\.\)]\s+/.test(t) ||
    t.endsWith("?") ||
    /^De ce /i.test(t) ||
    /^Ce /i.test(t) ||
    /^Când /i.test(t) ||
    /^Cum /i.test(t) ||
    /^Why /i.test(t) ||
    /^What /i.test(t) ||
    /^When /i.test(t) ||
    /^How /i.test(t) ||
    /^Почему /i.test(t) ||
    /^Что /i.test(t) ||
    /^Когда /i.test(t) ||
    /^Как /i.test(t) ||
    /^Чому /i.test(t) ||
    /^Що /i.test(t) ||
    /^Коли /i.test(t) ||
    /^Як /i.test(t)
  );
}

function looksLikePhone(text: string) {
  return /(\+373|022\s*60\s*50\s*60|79\s*422\s*908|079\s*422\s*908)/.test(text);
}

function looksLikeDisclaimer(text: string) {
  const t = text.toLowerCase();

  return (
    t.includes("articol") && t.includes("consulta") ||
    t.includes("revimed plus+ nu este centru oncologic") ||
    t.includes("nu înlocuiește") ||
    t.includes("nu inlocuieste") ||
    t.includes("онколог") ||
    t.includes("інформаційний") ||
    t.includes("informativ")
  );
}

function looksLikeImportant(text: string) {
  const t = text.toLowerCase();
  return (
    t.startsWith("important") ||
    t.startsWith("важно") ||
    t.startsWith("важливо") ||
    t.startsWith("un lucru important")
  );
}

function enhanceArticle() {
  if (!isBlogPostPage()) return;

  const content = document.querySelector<HTMLElement>(".blogReadableContent");
  const article = document.querySelector<HTMLElement>(".blogPostArticle, .blogArticleCard, article");

  if (!content || !article) return;
  if (content.dataset.enhanced === "true") return;

  content.dataset.enhanced = "true";

  const children = Array.from(content.children) as HTMLElement[];

  children.forEach((el, index) => {
    const text = normalize(el.textContent || "");
    if (!text) return;

    el.classList.add("blogPrettyParagraph");

    // First paragraph = intro box.
    if (index === 0) {
      el.classList.add("blogIntroBox");
      return;
    }

    if (looksLikeHeading(text)) {
      el.classList.remove("blogPrettyParagraph");
      el.classList.add("blogAutoHeading");
      if (!text.startsWith("✓")) {
        el.textContent = `✓ ${text}`;
      }
      return;
    }

    if (looksLikeImportant(text)) {
      el.classList.add("blogImportantBox");
      return;
    }

    if (looksLikeDisclaimer(text)) {
      el.classList.add("blogDisclaimerLine");
      return;
    }

    if (looksLikePhone(text)) {
      el.classList.add("blogPhoneLine");
      return;
    }

    // Highlight key medical words inside paragraph.
    const html = el.innerHTML;
    if (!el.dataset.marked) {
      el.innerHTML = html
        .replace(/\b(prevenția|prevenție|screeningul|screening|analize|oncomarker|markerii tumorali|fosfataza alcalină|medic|oncolog|simptome|diagnostic)\b/gi, '<mark class="blogAutoMark">$1</mark>')
        .replace(/\b(prevention|screening|blood tests|tumor markers|alkaline phosphatase|doctor|oncologist|symptoms|diagnosis)\b/gi, '<mark class="blogAutoMark">$1</mark>')
        .replace(/\b(профилактика|скрининг|анализы|онкомаркеры|щелочная фосфатаза|врач|онколог|симптомы|диагноз)\b/gi, '<mark class="blogAutoMark">$1</mark>')
        .replace(/\b(профілактика|скринінг|аналізи|онкомаркери|лужна фосфатаза|лікар|онколог|симптоми|діагноз)\b/gi, '<mark class="blogAutoMark">$1</mark>');
      el.dataset.marked = "true";
    }
  });

  addDownloadBox(article);
}

function buildDocumentHtml() {
  const lang = getLang();
  const label = labels[lang];

  const title =
    document.querySelector("section.blogPostHero h1")?.textContent?.trim() ||
    document.querySelector("h1")?.textContent?.trim() ||
    "Revimed PLUS+";

  const article = document.querySelector<HTMLElement>(".blogPostArticle, .blogArticleCard, article");
  const content = document.querySelector<HTMLElement>(".blogReadableContent");

  if (!article || !content) return null;

  const clone = content.cloneNode(true) as HTMLElement;
  clone.querySelectorAll(".blogExportBox, button, script, style").forEach((el) => el.remove());
  clone.querySelectorAll<HTMLElement>("[style]").forEach((el) => el.removeAttribute("style"));

  const image = article.querySelector<HTMLElement>(".postHeroImage");
  const imageStyle = image?.style.backgroundImage || "";
  const imageUrlMatch = imageStyle.match(/url\(["']?(.*?)["']?\)/);
  const imageUrl = imageUrlMatch?.[1] || "";

  const logo = `${window.location.origin}/images/logo.png`;

  return {
    title,
    filename: `${safeFileName(title)}-revimed.html`,
    html: `<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>${title}</title>
<style>
  body{
    margin:0;
    padding:34px;
    font-family:Arial, Helvetica, sans-serif;
    color:#10233f;
    background:#fff;
    line-height:1.65;
    font-size:15px;
  }
  .doc{
    max-width:760px;
    margin:0 auto;
  }
  .logoTop,
  .logoBottom{
    text-align:right;
    margin-bottom:24px;
  }
  .logoTop img,
  .logoBottom img{
    width:160px;
    height:auto;
  }
  h1{
    color:#08234a;
    font-size:32px;
    line-height:1.15;
    margin:0 0 22px;
  }
  .heroImg{
    width:100%;
    max-height:330px;
    object-fit:cover;
    border-radius:16px;
    margin:0 0 24px;
  }
  p{
    margin:0 0 14px;
  }
  .blogIntroBox,
  .blogAutoHeading,
  .blogImportantBox{
    padding:12px 14px;
    border-radius:10px;
    background:#eef8ff;
    border-left:4px solid #0b8fd8;
    font-weight:700;
    color:#08234a;
  }
  .blogDisclaimerLine{
    padding:12px 14px;
    border-radius:10px;
    background:#fff8ef;
    border-left:4px solid #f59e0b;
    font-weight:700;
  }
  .blogPhoneLine{
    padding:9px 12px;
    border-radius:999px;
    background:#eef8ff;
    border:1px solid #cfe7f8;
    font-weight:700;
  }
  mark{
    background:#fff3bf;
    padding:1px 4px;
    border-radius:4px;
  }
  .footerNote{
    margin-top:32px;
    padding-top:16px;
    border-top:1px solid #dcecf8;
    color:#64748b;
    font-size:13px;
  }
  @media print{
    body{ padding:20px; }
  }
</style>
</head>
<body>
  <div class="doc">
    <div class="logoTop"><img src="${logo}" alt="Revimed PLUS+"></div>
    <h1>${title}</h1>
    ${imageUrl ? `<img class="heroImg" src="${imageUrl}" alt="">` : ""}
    ${clone.innerHTML}
    <div class="footerNote">
      ${label.generated}<br>
      ${label.clinic}<br>
      022 60 50 60 · +373 79 422 908
    </div>
    <div class="logoBottom"><img src="${logo}" alt="Revimed PLUS+"></div>
  </div>
</body>
</html>`
  };
}

function downloadDocument() {
  const doc = buildDocumentHtml();
  if (!doc) return;

  const blob = new Blob(["\ufeff", doc.html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = doc.filename;
  document.body.appendChild(a);
  a.click();
  a.remove();

  window.setTimeout(() => URL.revokeObjectURL(url), 800);
}

function addDownloadBox(article: HTMLElement) {
  if (article.querySelector(".blogExportBox")) return;

  const lang = getLang();
  const label = labels[lang];

  const box = document.createElement("div");
  box.className = "blogExportBox";
  box.innerHTML = `
    <div class="blogExportText">
      <strong>${label.saveTitle}</strong>
      <span>${label.saveDesc}</span>
    </div>
    <button type="button" class="blogExportBtn">${label.saveBtn}</button>
  `;

  box.querySelector("button")?.addEventListener("click", downloadDocument);
  article.appendChild(box);
}

export default function BlogArticleEnhancer() {
  useEffect(() => {
    enhanceArticle();

    const observer = new MutationObserver(() => enhanceArticle());
    observer.observe(document.body, { childList: true, subtree: true });

    return () => observer.disconnect();
  }, []);

  return null;
}
